# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
# shellcheck disable=SC1090,SC1091

# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# XXX: Setting XDG variables now in .bash_profile
: ${XDG_CONFIG_HOME:?Warning: XDG variables are not set.}

# History Options

# Make bash append rather than overwrite the history on disk
shopt -s histappend

# When a history substitution fails, grant a chance to edit the failed history
# substitution.
shopt -s histreedit

# Do not the results of history substitution immediately pass to the shell
# parser.
shopt -s histverify

# Address multiline history entries well.
shopt -s cmdhist lithist

# Don't put duplicate lines or lines starting with space in the history. See
# bash(1) for more options
HISTCONTROL="ignoreboth"

# Define which command lines should not be saved in the history.
# - ?, ??: one and two character commands
HISTIGNORE='?:??:cd -:hibernate*:exit:pushd*:popd*:pwd:reboot*:shutdown*:which*'

# change ~/.bash_history
HISTFILE="$XDG_STATE_HOME/bash_history"

# set only HISTSIZE but not HISTFILESIZE
HISTSIZE=1000

# %F %T, or %+4Y-%m-%d %H:%M:%S
HISTTIMEFORMAT="%F %T "

# Mail Options
MAILCHECK=0

# Shell Options
#
# See man bash for more options...

# Prevent overwriting files with redirection.
set -o noclobber

# Automatically close file descriptors assigned using the {varname}rd syntax.
shopt -s varredir_close

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# When changing directory small typos can be ignored by bash
# for example, cd /vr/lgo/apaache would find /var/log/apache
shopt -s cdspell dirspell

# If set, the shell will check for running jobs before exiting.
shopt -s checkjobs

shopt -s no_empty_cmd_completion

# For better handling of glob patterns that do not match any files:
# - With nullglob, the pattern will expand to an empty string instead of
#   remaining unchanged.
# - With failglob, an error will be raised if a pattern does not match any
#   files.
shopt -s nullglob failglob

# Disable Ctrl-S and Ctrl-Q flow control.
stty -ixon

# make less more friendly for non-text input files, see lesspipe(1)
[[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"

# Comment out so that WSLg works fine
#if [[ -f /etc/resolv.conf ]]; then
#    export DISPLAY=$(grep -oP "(?<=nameserver ).+" /etc/resolv.conf):0.0
#    export XDG_RUNTIME_DIR=/tmp/xdg-runtime
#    export RUNLEVEL=3
#fi

case "$OSTYPE" in
    cygwin | msys)
        export BROWSER=cygstart
        ;;
    linux-gnu)
        if [[ -n "$WSL_DISTRO_NAME" ]]; then
            export BROWSER=wslview
        fi
        ;;
esac

export EDITOR='code --wait' # --new-window

# FCEDIT: the default editor for the fc builtin command.
FCEDIT=$EDITOR

# Git

# cf. EDITOR, VISUAL; core.editor in .gitconfig
export GIT_EDITOR=$EDITOR

# See .git-prompt.sh
# Show unstaged (*) and staged (+) changes.
export GIT_PS1_SHOWDIRTYSTATE="yes"

# Show if currently something is stashed.
export GIT_PS1_SHOWSTASHSTATE="yes"

# Show if there're untracked files.
#export GIT_PS1_SHOWUNTRACKEDFILES=

# Show the difference between HEAD and its upstream.
export GIT_PS1_SHOWUPSTREAM="verbose"

# Specify the separator between the branch name and the state symbol.
#export GIT_PS1_STATESEPARATOR=" "

# Show more information about the identity of commits checked out as a
# detached HEAD.
#export GIT_PS1_DESCRIBE_STYLE="default"

# Enable a colored hint about the current dirty state.
export GIT_PS1_SHOWCOLORHINTS="yes"

# Make __git_ps1 to do nothing in the case when the current directory is set
# up to be ignored by git.
#GIT_PS1_HIDE_IF_PWD_IGNORED=

declare git_tool_home="$XDG_CONFIG_HOME/git"
for f in git-prompt.sh git-completion.bash;
do
    test -f "$git_tool_home/$f" && source "$git_tool_home/$f"
done
unset f git_tool_home

# Readline
#
# INPUTRC: initialization file
INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"

# Locale
# n.b. To see which locales are supported, invoke: locale -a
#
# LANG: the locale category for any category not specifically selected with a
# variable starting with LC_.
export LANG=C.utf8

# LC_ALL: overrides the value of LANG and any other LC_ variable specifying a
# locale category.
export LC_ALL=C.utf8

# less
#
# LESSHISTFILE: if set to "-" or "/dev/null", a history file is not used. The
# default is "$XDG_DATA_HOME/lesshst" or "$HOME/.lesshst".
export LESSHISTFILE=-

# man
if [ -x "$(command -v bat)" ]; then
    # bat <https://github.com/sharkdp/bat>
    export MANPAGER="bat --strip-ansi=auto -plman"
fi

# AWS
# <https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html>
# <https://github.com/aws/aws-sdk/issues/30>
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"
export AWS_CLI_HISTORY_FILE="$XDG_DATA_HOME/aws/history"
export AWS_CREDENTIALS_FILE="$XDG_DATA_HOME/aws/credentials"
export AWS_WEB_IDENTITY_TOKEN_FILE="$XDG_DATA_HOME/aws/token"
export AWS_SHARED_CREDENTIALS_FILE="$XDG_DATA_HOME/aws/shared-credentials"

# Azure CLI
export AZURE_CONFIG_DIR="$XDG_DATA_HOME/azure" # not XDG_CONFIG_HOME?

# <https://github.com/sharkdp/bat>
export BAT_STYLE=header,numbers,changes,snip,rule

# Docker
# <https://docs.docker.com/engine/reference/commandline/cli/>
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export DOCKER_HIDE_LEGACY_COMMANDS=hide

# eza <https://eza.rocks/>
export EZA_STRICT=yes

# <https://fx.wtf/configuration>
export FX_SHOW_SIZE=true
export FX_LINE_NUMBERS=true
export FX_COLLAPED=true
export FX_INDENT=4

# fzf <https://junegunn.github.io/fzf/>
export FZF_DEFAULT_OPTS_FILE="$XDG_CONFIG_HOME/fzf/fzfrc"

# fzf-git.h <https://github.com/junegunn/fzf-git.sh/>
export FZF_GIT_SH="$XDG_CONFIG_HOME/fzf/fzf-git.sh"

# Kubernetes
export KUBECONFIG="$XDG_CONFIG_HOME/kube"
export KUBECACHEDIR="$XDG_CACHE_HOME/kube"

# Minikube
# Creates a further .minikube directory in MINIKUBE_HOME for whatever reason.
export MINIKUBE_HOME="$XDG_DATA_HOME/minikube"

# Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
[[ -s "$CARGO_HOME/env" ]] && source "$CARGO_HOME/env"

# Ruby Gems bundler
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle"
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/bundle"
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"

# XDG_CONFIG_HOME/gemrc

# XDG_CONFIG_HOME/irb
export IRBRC="$XDG_CONFIG_HOME/irb/irbrc"

export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

# XDG_DATA_HOME/rdoc

# MySQL
export MYSQL_HISTFILE="$XDG_STATE_HOME/mysql_history"

# Node.js
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl_history"

# npm
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

# NuGet (only ~/.nuget/packages)
export NUGET_PACKAGES="$XDG_CACHE_HOME/NuGetPackages"

# PostgreSQL
export PSQLRC="$XDG_CONFIG_HOME/postgresql/psqlrc"
export PSQL_HISTORY="$XDG_STATE_HOME/postgresql/psql_history"

# PulseAudio
export PULSE_COOKIE="$XDG_CACHE_HOME/pulse/cookie"

# Pylint
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export PYLINTRC="$XDG_CONFIG_HOME/pylint/pylintrc"

# Python
export PYTHON_HISTORY="$XDG_STATE_HOME/python/history"
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc.py"
export PYTHONUSERBASE="$XDG_DATA_HOME/python"

# IPython and Jupyter
# <https://github.com/jupyter/notebook/issues/2374#issuecomment-551765192>
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"

# Matplotlib
export MATPLOTLIBRC="$XDG_CONFIG_HOME/matplotlib"

# SQLite
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"

# Vim
# shellcheck disable=SC2016
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# wget
export WGETRC="$XDG_CONFIG_HOME/wgetrc"

# TMP and TEMP are defined in the Windows environment.  Leaving
# them set to the default Windows temporary directory can have
# unexpected consequences.
# Alternatively, set them to the Cygwin temporary directory
# or to any other tmp directory of your choice
case "$OSTYPE" in
    cygwin | msys)
        unset TMP TEMP
        export TMP=/tmp TEMP=/tmp
        TMPDIR=/tmp
        ;;
    *) ;;
esac

# CONDARC must be a path to a file named .condarc, condarc, or end with a YAML
# suffix (.yml or .yaml).
export CONDARC="$XDG_CONFIG_HOME/conda/condarc.d/.condarc"

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba shell init' !!
export MAMBA_EXE="$XDG_DATA_HOME/conda/envs/python-3.14/bin/mamba"
export MAMBA_ROOT_PREFIX="$XDG_DATA_HOME/conda"
if __mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"; then
    eval "$__mamba_setup"
else
    alias mamba='$MAMBA_EXE'  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<

# Homebrew
# - Define HOMEBREW_PREFIX, HOMEBREW_CELLAR, HOMEBREW_REPOSITORY.
# - Modify PATH, MANPATH, INFOPATH.
for dir in "$HOME/.linuxbrew" "/home/linuxbrew/.linuxbrew"; do
    if [[ -d "$dir" ]] ; then
        eval "$("${dir}/bin/brew" shellenv)"

        # <https://docs.brew.sh/Shell-Completion>
        declare f="${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
        if [[ -r "$f" ]]; then
            source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
            break

        for f in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
            [[ -r "$f" ]] && source "$f"
            done
        fi
        unset f
        break
    fi
done
unset dir

# Enable Oh My Posh
if [[ -x "$(command -v oh-my-posh)" ]]; then
    # post-condition: [[ "$POSH_THEME" == "$XDG_CONFIG_HOME/oh-my-posh.json" ]]
    eval "$(oh-my-posh init bash --config "$XDG_CONFIG_HOME/oh-my-posh.json")"

    function set_poshcontext {
        export CURRENT_HISTORY_NUMBER="$HISTCMD"
    }
fi

# Enable Pipenv completion
[[ -x "$(command -v pipenv)" ]] && eval "$(_PIPENV_COMPLETE=bash_source pipenv)"

# Enable Hatch completion
[[ -x "$(command -v hatch)" ]] && eval "$(_HATCH_COMPLETE=bash_source hatch)"

# Enable Ruff completion
[[ -x "$(command -v ruff)" ]] && eval "$(ruff generate-shell-completion bash)"

# Initialize fzf
[[ -x "$(command -v fzf)" ]] && eval "$(fzf --bash)"

# Initialize zoxide
[[ -x "$(command -v zoxide)" ]] && eval "$(zoxide init --cmd cd bash)"

# WIP
function nvm {
    unset -f nvm

    # Use XDG_DATA_HOME instead of XDG_CONFIG_HOME
    export NVM_DIR="$XDG_DATA_HOME/nvm"

    # want to manually run `nvm use`
    [[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh" --no-use
    [[ -s "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"
    # run the authentic nvm
    nvm "$@"
}

# original code by Bash Guide for Beginners
function _munge_path
{
    local -r a_path="$1"
    local -r first_or_last="${2-}"

    if [[ ! -d "$a_path" ]]; then
        echo "Warning: $a_path is not directory." >&2
        return 1
    fi

    if [[ $PATH =~ (^|:)$a_path($|:) ]] ; then
        return 0
    fi

    if [[ $first_or_last == first ]]; then
        PATH="$a_path${PATH:+:${PATH}}"
    else
        PATH="${PATH:+${PATH}:$a_path}"
    fi
}

case "$OSTYPE" in
    linux*)
        CDPATH=$(wslpath "$(wslvar USERPROFILE)")

        test -v GEM_HOME && _munge_path "$GEM_HOME/bin" first

        if [[ -n "$WSL_DISTRO_NAME" ]]; then
            _munge_path "$(wslpath "$(wslvar PROGRAMFILES)")/Microsoft VS Code/bin"

            system32_path=$(wslpath "$(wslvar SystemRoot)/System32")
            EXECIGNORE="${system32_path}/*.!(exe)"
            unset system32_path
        fi
        ;;
    *)
        echo "Warning: $OSTYPE not supported" >&2
        ;;
esac

# set PATH so that it includes user's private bin
for private_dir in "$HOME/.local/bin" "$HOME/bin"; do
    if [[ -d "$private_dir" ]] ; then
        _munge_path "$private_dir" first
        break
    fi
done
unset private_dir
unset -f _munge_path

# Alias and functions.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
declare bash_config_home="$XDG_CONFIG_HOME/bash"
for f in bash_aliases bash_functions; do
    if [[ -f "$bash_config_home/$f" ]]; then
        source "$bash_config_home/$f"
    else
        source "$HOME/$f"
    fi
done
unset f bash_config_home
