# ~/.bash_profile: executed by bash(1) for login shells.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
umask 022

# source the users bashrc if it exists
declare bash_config_home="${XDG_HOME_CONFIG:-$HOME/.config}/bash"
if [[ -f "$bash_config_home/bashrc" ]]; then
    # shellcheck disable=SC1091
    source "$bash_config_home/bashrc"
elif [[ -f "$HOME/.bashrc" ]]; then
    # shellcheck disable=SC1091
    source "$HOME/.bashrc"
fi
unset bash_config_home

# SSH
# For detailed information, see <https://www.funtoo.org/Funtoo:Keychain>.
eval "$(keychain --agents ssh --quiet --eval id_ed25519)"
