# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# Honor XDG_*_HOME
# See XDG Base Directory Specification
# <https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html>
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache

# History Options

# Make bash append rather than overwrite the history on disk
shopt -s histappend

# When a history substitution fails, grant a chance to edit the failed history
# substitution.
shopt -u histreedit

# Do not the results of history substitution immediately pass to the shell
# parser.
shopt -s histverify

# multi-line commands are saved to the history with embedded newlines rather
# than using semicolon separators where possible.
shopt -s lithist

# Don't put duplicate lines or lines starting with space in the history. See
# bash(1) for more options
HISTCONTROL="ignoreboth"

# Ignore some controlling instructions
# The '&' is a special pattern which suppresses duplicate entries.
HISTIGNORE=$'[ \t]*:&:?:[fb]g:hibernate*:exit:which.+'

# change ~/.bash_history
HISTFILE="$XDG_STATE_HOME/bash_history"

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# %F %T, or %+4Y-%m-%d %H:%M:%S
HISTTIMEFORMAT="%F %T "

# Shell Options
#
# See man bash for more options...

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Don't wait for job termination notification
# set -o notify

# Don't use ^D to exit
# set -o ignoreeof

# Use case-insensitive filename globbing
# shopt -s nocaseglob

# When changing directory small typos can be ignored by bash
# for example, cd /vr/lgo/apaache would find /var/log/apache
shopt -s cdspell dirspell

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Comment out so that WSLg works fine
#if [[ -f /etc/resolv.conf ]]; then
#    export DISPLAY=$(grep -oP "(?<=nameserver ).+" /etc/resolv.conf):0.0
#    export XDG_RUNTIME_DIR=/tmp/xdg-runtime
#    export RUNLEVEL=3
#fi

case "$OSTYPE" in
    cygwin | msys)
        export BROWSER=cygstart
        ;;
    linux-gnu)
        if [[ -n "$WSL_DISTRO_NAME" ]]; then
            export BROWSER=wslview
        fi
        ;;
esac

export EDITOR='code --wait' # --new-window

# FCEDIT: the default editor for the fc builtin command.
export FCEDIT=$EDITOR

# Git

export GIT_EDITOR=$EDITOR

# See .git-prompt.sh
# Show unstaged (*) and staged (+) changes.
GIT_PS1_SHOWDIRTYSTATE="yes"

# Show if currently something is stashed.
GIT_PS1_SHOWSTASHSTATE="yes"

# Show if there're untracked files.
#GIT_PS1_SHOWUNTRACKEDFILES=

# Show the difference between HEAD and its upstream.
GIT_PS1_SHOWUPSTREAM="verbose"

# Specify the separator between the branch name and the state symbol.
#GIT_PS1_STATESEPARATOR=" "

# Show more information about the identity of commits checked out as a
# detached HEAD.
#GIT_PS1_DESCRIBE_STYLE="default"

# Enable a colored hint about the current dirty state.
GIT_PS1_SHOWCOLORHINTS="yes"

# Make __git_ps1 to do nothing in the case when the current directory is set
# up to be ignored by git.
#GIT_PS1_HIDE_IF_PWD_IGNORED=

declare git_tool_home="$XDG_CONFIG_HOME/git"
for f in git-prompt.sh git-completion.sh;
do
    test -f "$git_tool_home/$f" && source "$git_tool_home/$f"
done
unset f git_tool_home

# grep's default options
#export GREP_OPTIONS='--color=auto'

# ~/.inputrc
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"

# Locale
#
# LANG: the locale category for any category not specifically selected
# with a variable starting with LC_.
export LANG=ja_JP.UTF-8

# LC_ALL: overrides the value of LANG and any other LC_ variable
# specifying a locale category.
export LC_ALL=

#LC_COLLATE
#LC_CTYPE
#LC_MESSAGES
#LC_NUMERIC

# less
export LESSHISTFILE=-

# Docker (only config.json?)
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"

export AZURE_CONFIG_DIR="$XDG_DATA_HOME/azure"

# Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
[ -s "$CARGO_HOME/env" ] && source "$CARGO_HOME/env"

# Ruby Gems bundler
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle"
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/bundle"
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"

# XDG_CONFIG_HOME/gemrc

# XDG_CONFIG_HOME/irb
export IRBRC="$XDG_CONFIG_HOME/irb/irbrc"

export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

# XDG_DATA_HOME/rdoc

# MySQL
export MYSQL_HISTFILE="$XDG_STATE_HOME/mysql_history"

# Node.js
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl_history"

# npm
export NPM_CONFIG_USERCONFIG="$MY_CONFIG_HOME/npm/npmrc"

# NuGet (only ~/.nuget/packages)
export NUGET_PACKAGES="$XDG_CACHE_HOME/NuGetPackages"

# Oh My Posh
export POSH_THEME="$XDG_CONFIG_HOME/oh-my-posh.json"

#export PATH

# Prompt
# See .git-prompt.sh
#export PROMPT_COMMAND="__git_ps1; $PROMPT_COMMAND"

# PS1: the primary prompt string.
#export PS1='[$OSTYPE \s \W \!]\\$ '
#export PS1='\u@\h \w> '
export PS2='> '

# PS3: the prompt for the select command
# export PS3

# PS4: the value is printed before each command bash displays during
# an execution trace, e.g. `set -x`, `bash -x script.sh`, etc.
# export PS4

# Pylint
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export PYLINTRC="$XDG_CONFIG_HOME/pylint/pylintrc"

# Python
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc.py"
export PYTHONUSERBASE="$XDG_DATA_HOME/python"

# SQLite
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"

# Vim
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# wget
export WGETRC="$XDG_CONFIG_HOME/wgetrc"

# TMP and TEMP are defined in the Windows environment.  Leaving
# them set to the default Windows temporary directory can have
# unexpected consequences.
unset TMP
unset TEMP

# Alternatively, set them to the Cygwin temporary directory
# or to any other tmp directory of your choice
export TMP=/tmp
export TEMP=/tmp

# Or use TMPDIR instead
export TMPDIR=/tmp

export TZ=JST-09

# Alias and functions.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
declare bash_config_home="$XDG_CONFIG_HOME/bash"
for f in bash_aliases bash_functions; do
    if [ -f "$bash_config_home/$f" ]; then
        source "$bash_config_home/$f"
    else
        source "$HOME/$f"
    fi
done
unset f
unset bash_config_home

# >>> conda initialize >>>
declare __conda_home="$XDG_DATA_HOME/miniconda3"
declare __conda_setup="$($__conda_home/bin/conda shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$__conda_home/etc/profile.d/conda.sh" ]; then
        source "$__conda_home/etc/profile.d/conda.sh"
    else
        PATH="$__conda_home/bin:$PATH"
    fi
fi
unset __conda_setup __conda_home
conda activate python-3.11
# <<< conda initialize <<<

# WIP
nvm() {
    unset -f nvm

    # Use XDG_DATA_HOME instead of XDG_CONFIG_HOME
    export NVM_DIR="$XDG_DATA_HOME/nvm"

    # want to manually run `nvm use`
    [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh" --no-use
    [ -s "$NVM_DIR/bash_completion" ] && source "$NVM_DIR/bash_completion"
    # run the authentic nvm
    nvm $@
}
